### ISSUE TITLE
Link to "evolving tutorial" on Hackage is dead

### ISSUE THREAD

**Issue by beerendlauwers** [gridaphobe/target#4]
http://hackage.haskell.org/package/target-0.1.3.0 links to http://github.com/ucsd-progsys/liquidhaskell/tree/master/docs/tutorial. This link is dead. You can only get up to https://github.com/ucsd-progsys/liquidhaskell/tree/master/docs.

**Comment by gridaphobe** [comment]
Thanks for the report! The tutorial is now at https://github.com/ucsd-progsys/liquidhaskell-tutorial, I'll update the cabal docs.
